require "rake/testtask"
task default: "test"

Rake::TestTask.new do |task|
  task.warning = false
  # task.pattern = FileList["gather_input_udt_test/test*.rb",
  #                         "gather_input_ckb_test/test*.rb",
  #                         "making_payment_udt_test/test*.rb",
  #                         "making_payment_ckb_test/test*.rb",
  #                         "closing_channel_test/test*.rb"]
  # task.pattern = FileList["gather_input_udt_test/test*.rb"]
  # task.pattern = FileList["gather_input_ckb_test/test*.rb"]
  # task.pattern = FileList["making_payment_udt_test/test*.rb"]
  # task.pattern = FileList["making_payment_ckb_test/test*.rb"]
  # task.pattern = FileList["closing_channel_test/test*.rb"]
  # task.pattern = FileList["step1_ckb_test/test*.rb"]
  # task.pattern = FileList["step2_ckb_test/test*.rb"]
  # task.pattern = FileList["step3_ckb_test/test*.rb"]
  task.pattern = FileList["step4_ckb_test/test*.rb"]
end
